### ISSUE TITLE
`skip_fixed_array_length` not found during compiling

### ISSUE THREAD

**Issue by Fannxy** [AarhusCrypto/Ramen#1]
Hi~ 

I am new to your Ramen project. During the running the command `cargo run --release --example=bench_doram`, it raises the following error during the compiling:

```
error[E0599]: no method named `skip_fixed_array_length` found for struct `Configuration` in the current scope
  --> communicator/src/communicator.rs:30:41
   |
30 |             bincode::config::standard().skip_fixed_array_length(),
   |                                         ^^^^^^^^^^^^^^^^^^^^^^^ method not found in `Configuration`
```

Do you have any idea about this error? my rust version is 1.18.1

**Comment by lenerd** [comment]
Hi,
the issue is that this method was removed in bincode `v2.0.0-rc.3`. It works with `v2.0.0-rc.2`, though. I pushed a fix pinning this version (a8d9b7bcf5b00517c155d5e164242a924066cb73).

**Comment by Fannxy** [comment]
thanks, it seems that i did not pull to the latest master.

**Comment by lenerd** [comment]
No, I forgot to push the last few commits to the public repository. :)

**Comment by Fannxy** [comment]
23333 i thought my git has some problems

09/22/2024 22:37:16 "Lennart Braun" ***@***.***> wrote:

No, I forgot to push the last few commits to the public repository. :)
